### ISSUE TITLE
PHP error appear when we activate the GNPublisher pro verion

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/gn-publisher#55] opened 2023-05-08 11:33 UTC
Ref ticket:-https://magazine3.in/conversation/137360?folder_id=21

Description:-
When we check with the help of Plugin Query Monitor php error appears 

Issue screenshot:-
https://prnt.sc/Ai8OXLuSmgLq
https://monosnap.com/direct/OrCIVef6adiRNViuhNVvK7vzZnbrDI

Location:
wp-content/plugins/gn-publisher-pro-1.0.1/includes/common-helper.php:70
gnpub_setup_form_render()
wp-includes/class-wp-hook.php:308
do_action('gnpub_pro_setup_form')
wp-content/plugins/gn-publisher/templates/settings.php:414
GNPUB_Menu->display_settings_page()
wp-includes/class-wp-hook.php:308
do_action('settings_page_gn-publisher-settings')
wp-admin/admin.php:259

**Comment by muslimakhan** [comment] 2023-05-10 07:23
Issue is not recreated as user send query so we have to cross check from user license detail why our server is blocking that user's license key.

**Comment by Sanjeevsetu** [comment] 2024-04-09 10:42
The issue is not being re created at our end and since than we have improved the pro extension more. I am closing the ticket.

**Closed by Sanjeevsetu** 2024-04-09 10:42 UTC
Labels: bug, high, need more data
